### ISSUE TITLE
switch to another newsletter provider

### ISSUE THREAD

**Issue by cbrake** [YoeDistro/yoedistro.org#8]
tinyletter (mailchimp) is not responding to my support requests, so I think it is time to switch to someone else like convertkit.

**Comment by cbrake** [comment]
tinyletter did respond to both requests -- just takes 2 days or so. I also looked at convertkit, and embedding their forms is significantly more complex:

https://github.com/YoeDistro/yoedistro.org/commit/a53bf7ac9308af95171cbe95b87014ee6b7ed437

I did ask tinyletter about customizing their embedded form (including removing the link), and sounds like that is OK:

> Hi, Cliff.
> 
> Thanks for writing in to Support. If you're using the link for the signup form that we host there, that page is pretty limited in terms of what can be edited or changed out from within the account. However, if you're using your embed code that can be modified pretty extensively. If you're familiar with form-related coding you can absolutely make changes to that code for use on your site, including removing the link to TinyLetter, though you'd want to be sure to do some testing to ensure the form works as anticipated (we're unable to help troubleshoot custom code on a website, unfortunately).
> 
> Let us know if there's anything else we can help with!
> 
> Thanks,
> 
> Sean
> 

Although convertkit is a much more capable platform than tinyletter, I think tinyletter will suffice for our purposes (simply keep people up to date with what is going on). We're not trying to sell stuff, etc. Additionally, tinyletter gives us 5000 subscribers and convertkit, we'd need to start a paid subscription at 1000 or less. Since we don't have any sponsers for yoedistro (other than our own efforts), I think going with tinyletter makes sense from a cost perspective.

@kraj, @kdsch -- let me know if you think any differently.

**Comment by cbrake** [comment]
Since tinyletter is gracious enough to provide this service for free, perhaps we should consider keeping a link, but perhaps make it a lot smaller, and somehow indicate tinyletter is only powering the newsletter, not the entire site/project.

**Comment by kdsch** [comment]
@cbrake I agree; sounds like TinyLetter works. And I agree, the TL link could be misleading.

Possibilities:
- Smaller font for the TL link, as @cbrake suggests
- Lighter color for the TL link
- Increase space between the first paragraph and the "Looking for tips" pitch, which clarifies that the form is separate
- Move the TL link closer to the "Sign me up!" button.
- Add a footer section preceded by enough whitespace, to distinguish between the TL link and the page footer.

**Comment by kraj** [comment]
I agree lets keep using tiny letter if this is the case. and I agree about mentioning them
